version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  build:
    commands:
      - echo "Building the application"
      - npm install
      - npm run build
      - zip -r my-artifact.zip build/

artifacts:
  files:
    - my-artifact.zip

