name: Upload Build Folder to S3

on:
  push:
    branches:
      - production  # Change this to your branch name if needed

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::767397935218:role/counter-s3   # Replace with your IAM role ARN
        aws-region: ap-south-1  # Change this to your AWS region

    - name: Upload to S3
      run: aws s3 sync build/ s3://counters3bucket/build/
