name: Upload Build Folder to S3

on:
  push:
    branches:
      - main  # Change this to your branch name if needed

jobs:
  upload_to_s3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: 
         ref: production
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-south-1  # Replace with your region
      - name: Upload Build Folder to S3
        uses: aws-actions/amazon-s3-copy@v1
        with:
          source: ./build  # Replace with your build folder path
          bucket: counters3bucket  # Replace with your bucket name
          acl: public-read  # Optional: Set object ACL

