name: Upload Build Folder to S3

on:
  push:
    branches:
      - main  # Change this to your branch name if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: production

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        role-to-assume: arn:aws:iam::767397935218:role/counter-s3  # Replace with your IAM role ARN
        aws-region: ap-south-1  # Change this to your AWS region

    - name: Upload to S3
      run: aws s3 sync build/ s3://counters3bucket/build/
